services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: risk-analise
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
